baseURL = "https://withdtlabs.github.io/docs/"
title = "CloudZ Labs"
theme = "labs"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""
disqusShortname = "labs-tech-blog"
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Cloud의 시작. CloudZ Labs와 함께 하세요."
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["assets/css/bootstrap.css", "assets/css/common.css", "assets/css/font-awesome.css"]
customJS = ["assets/js/common.js", "assets/js/scripts.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = "Copyright"
holder = "CloudZ Labs"
startYear = "2018"
suffix = "All Rights Reserved."

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 3
latestPostsLength = 7
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
homepageSections = ["main-posts", "latest-posts"]

# Enable / Disable algolia search
algolia_search    = true
algolia_appId     = "Y2C4RWMPXW"
algolia_apiKey    = "50ea7f8c41c0ad233926e0be2b769ed1"
algolia_indexName = "default-content"

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
google = "dtlabs"
facebook = "dtlabs"
twitter = "dtlabs"
github-alt = "dtlabs"
email = "withdtlabs@gmail.com"

[params.social.config]
platforms = ["google", "twitter", "facebook", "github-alt"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Posts"
weight = -10
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "Registration"
weight = 10
identifier = "labs"
url = "http://cloudz-labs.sk.com"

[languages]
# edit this block for your own language
[languages.en]
lang = "ko"
languageName = "Korean"
weight = 1
