baseURL = "https://cloudzlabs.github.io/docs/"
title = "CloudZ Labs Tech"
theme = "labs"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""
disqusShortname = "cloudz-labs"
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

disableInlineCopyToClipBoard = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "ko"

[blackfriday]
hrefTargetBlank = true

[params.info]
description = ""
title404 = "Nothing's here!"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params.assets]
favicon = "favicon-blank.ico"
customCSS = ["assets/css/bootstrap.css", "assets/css/common.css", "assets/css/font-awesome.css", "assets/css/markdown.css", "assets/css/mermaid.css", "assets/css/mermaid.dark.css", "assets/css/mermaid.forest.css"]
customJS = ["assets/js/common.js", "assets/js/scripts.js", "assets/js/lunr.min.js", "assets/js/auto-complete.js", "assets/js/search.js", "assets/js/clipboard.min.js", "assets/js/mermaid.js"]

[params.copyright]
prefix = "Copyright"
holder = "CloudZ Labs"
startYear = "2018"
suffix = "All Rights Reserved."

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 3
latestPostsLength = 7
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
homepageSections = ["main-posts", "latest-posts"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "|"

[params.social]
facebook = "cloudzlabs"
twitter = "cloudzlabs"
github-alt = "cloudzlabs"
email = "withdtlabs@gmail.com"

[params.social.config]
platforms = ["twitter", "facebook", "github-alt", "email"]

[params.social.share]
# Sets Social Share links to appear on posts
enabled = true
# Sets specific share to appear on posts (default behavior is to appear)
twitter = true
google = true
facebook = true
linkedin = true
pinterest = true
email = true

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Posts"
weight = -10
identifier = "posts"
url = "/posts/"

[languages]
# edit this block for your own language
[languages.ko]
lang = "ko"
languageName = "Korean"
weight = 1

[related]
# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 80
# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = true
# Will lower case keywords in both queries and in the indexes.
toLower = true

[[related.indices]]
name = "posts"
weight = 150
[[related.indices]]
name  = "author"
toLower = true
weight = 30
[[related.indices]]
name  = "tags"
weight = 100
